import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

const Layout = ({children, title}) => {
    return(
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       {children} 
      </main>
    </div>
    );
}

export default Layout;